# Generated by Django 3.0.7 on 2020-06-11 08:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docid', models.IntegerField()),
                ('title', models.TextField()),
                ('titleEng', models.TextField()),
                ('directorEnNm', models.CharField(max_length=100)),
                ('directorNm', models.CharField(max_length=100)),
                ('nation', models.CharField(max_length=100)),
                ('prodYear', models.DateTimeField(auto_now_add=True)),
                ('plot', models.TextField()),
                ('runtime', models.IntegerField()),
                ('ratingGrade', models.TextField()),
                ('genre', models.CharField(max_length=100)),
                ('releaseDate', models.DateTimeField(auto_now_add=True)),
                ('keywords', models.TextField()),
                ('posterUrl', models.TextField()),
                ('stillUrl', models.TextField()),
                ('vodUrl', models.TextField()),
                ('audiAcc', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
