# Generated by Django 3.0.7 on 2020-06-12 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_hits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='title',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='updated_at',
        ),
    ]
