# Generated by Django 3.0.7 on 2020-06-13 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20200612_1235'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
