# Generated by Django 3.0.7 on 2020-06-13 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('titleEng', models.CharField(max_length=100)),
                ('directors', models.CharField(max_length=100)),
                ('nation', models.CharField(max_length=100)),
                ('plots', models.TextField()),
                ('runtime', models.IntegerField()),
                ('rating', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=100)),
                ('repRlsDate', models.DateTimeField(auto_now_add=True)),
                ('keywords', models.TextField()),
                ('posters', models.TextField()),
                ('stlls', models.TextField()),
                ('vods', models.TextField()),
                ('audiAcc', models.FloatField()),
            ],
        ),
    ]
