# Generated by Django 3.0.7 on 2020-06-15 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('DOCID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('titleEng', models.CharField(max_length=100)),
                ('nation', models.CharField(max_length=100)),
                ('runtime', models.IntegerField()),
                ('rating', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=100)),
                ('repRlsDate', models.DateTimeField(auto_now_add=True)),
                ('keywords', models.TextField()),
                ('posters', models.TextField()),
                ('stlls', models.TextField()),
                ('audiAcc', models.FloatField()),
                ('directorNm', models.CharField(max_length=100, null=True)),
                ('directorEnNm', models.CharField(max_length=100)),
                ('plotLang', models.CharField(max_length=20, null=True)),
                ('plotText', models.TextField()),
                ('vodUrl', models.TextField()),
            ],
        ),
    ]
