# Generated by Django 3.0.7 on 2020-06-14 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='DOCID',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
