# Generated by Django 3.0.7 on 2020-06-15 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20200615_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='audiAcc',
            field=models.FloatField(null=True),
        ),
    ]
