# Generated by Django 3.0.7 on 2020-06-14 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_docid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='directors',
            new_name='directorEnNm',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='plots',
            new_name='plotText',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='vods',
            new_name='vodUrl',
        ),
        migrations.AddField(
            model_name='movie',
            name='directorNm',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='plotLang',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
