# Generated by Django 3.0.7 on 2020-06-14 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20200614_2250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='DOCID',
        ),
    ]
