# Generated by Django 3.0.7 on 2020-06-15 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20200615_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='audiAcc',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
