# Generated by Django 3.0.7 on 2020-06-15 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20200615_0924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='audiAcc',
        ),
    ]
